# Generated by Django 5.1.3 on 2025-02-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_description_job_experince_job_job_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catecory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
